apiVersion: v1
kind: Service
metadata:
  name: webpage-to-pdf-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: webpage-to-pdf-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-to-pdf-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webpage-to-pdf-api
  template:
    metadata:
      labels:
        app: webpage-to-pdf-api
    spec:
      imagePullSecrets:
        - name: sublayer-gitlab-creds
      containers:
        - name: webpage-to-pdf-api
          image: registry.gitlab.com/sublayer/sublayer/webpage-to-pdf-api:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
